### ISSUE TITLE
Crash on Select Directory

### ISSUE THREAD

**Issue by jhoman81** [Noppadet/Emulation-Manager#3]
Application crashes when the select directory (...) button is pressed when Ookii.Dialogs.Wpf.dll is not present on Windows 10.

**Comment by fran122157** [comment]
I manage to fix this dragging the directory from windows manager to the "select directory box"

**Comment by NVRemoteDev** [comment]
Thanks I'll fix this in the next release along with adding Grid images support. In the meantime you can find the correct dll in the previous release, which you can put in the Tritium directory. Hopefully that will take care of it.

**Comment by fran122157** [comment]
Glad to hear this is getting attention! Are there any news on when we will have available the option to download grid images?

Great work btw!

**Comment by NVRemoteDev** [comment]
Thank you! Grid images will definitely be coming in the next release; perhaps as soon as this weekend (but no promises).

**Comment by fran122157** [comment]
hahaha. already glad that this project hasn't been abandoned. I visited the hometheatertablet website yesterday and saw it was down, didn't know what to think. Thanks for the response!

**Comment by NVRemoteDev** [comment]
No it's still alive I didn't realize the website was down. That should be taken care of shortly. Look forward to Grid images in the very near future.

**Comment by fran122157** [comment]
Bump.

**Comment by NVRemoteDev** [comment]
fran122157 - I'll be porting this to a new version shortly. I'll try to clean up all the bugs mentioned so far, and it will have the grid images for sure.

**Comment by fran122157** [comment]
Nice!

I´m super excited about this tool, I´m not so excited about adding grid images manually to a 2000 rom library though, therefore my interest in your project hahaha

Thanks for the feedback man! thought this was dead

**Comment by Jmo687** [comment]
Glad to see this project is still alive.  I just used this with my nexus player and moonlight...worked fantastic!  Nexus gamepad even worked with ps2 and your shield controller config.  Very impressive!

**Comment by fran122157** [comment]
Any news??? It´s been over 3 months lol

**Comment by NVRemoteDev** [comment]
Unfortunately this is low on the priority list at the moment. Feel free to make a pull though if you want to help out; I'm always open to merging in code. If not I'll get to it when I find some extra time.

**Comment by NVRemoteDev** [comment]
This should now be fixed. I will update the release after a few more changes I'd like to make.
